[CAN]
; CAN ID配置（静态标定）
; 左前雷达
left_front_static_send_id = 0x61
left_front_static_recv_id = 0x71
; 右前雷达
right_front_static_send_id = 0x261
right_front_static_recv_id = 0x271
; 左后雷达
left_rear_static_send_id = 0x461
left_rear_static_recv_id = 0x471
; 右后雷达
right_rear_static_send_id = 0x661
right_rear_static_recv_id = 0x671

; CAN ID配置（参数标定）
; 左前雷达
left_front_param_send_id = 0x60
left_front_param_recv_id = 0x70
; 右前雷达
right_front_param_send_id = 0x260
right_front_param_recv_id = 0x270
; 左后雷达
left_rear_param_send_id = 0x460
left_rear_param_recv_id = 0x470
; 右后雷达
right_rear_param_send_id = 0x660
right_rear_param_recv_id = 0x670


[LeftFrontRadar]
; 左前雷达标定参数
vehicle_height = 0.5        ; 车辆高度（米）
x_offset = 2.5              ; X轴偏移量（米，车辆前进方向）
y_offset = -0.8             ; Y轴偏移量（米，车辆横向,左正右负）
z_offset = 0.3              ; Z轴偏移量（米，垂直方向，向上为正）
yaw_angle = 0.0             ; 偏航角（度）
pitch_angle = 0.0           ; 俯仰角（度）
roll_angle = 0.0            ; 翻滚角（度）

[RightFrontRadar]
; 右前雷达标定参数
vehicle_height = 0.5        ; 车辆高度（米）
x_offset = 2.5              ; X轴偏移量（米，车辆前进方向）
y_offset = 0.8              ; Y轴偏移量（米，车辆横向，左正右负）
z_offset = 0.3              ; Z轴偏移量（米，垂直方向，向上为正）
yaw_angle = 0.0             ; 偏航角（度）
pitch_angle = 0.0           ; 俯仰角（度）
roll_angle = 0.0            ; 翻滚角（度）

[LeftRearRadar]
; 左后雷达标定参数
vehicle_height = 0.5        ; 车辆高度（米）
x_offset = 2.5              ; X轴偏移量（米，车辆前进方向）
y_offset = -0.8             ; Y轴偏移量（米，车辆横向,左正右负）
z_offset = 0.3              ; Z轴偏移量（米，垂直方向，向上为正）
yaw_angle = 0.0             ; 偏航角（度）
pitch_angle = 0.0           ; 俯仰角（度）
roll_angle = 0.0            ; 翻滚角（度）

[RightRearRadar]
; 右后雷达标定参数
vehicle_height = 0.5        ; 车辆高度（米）
x_offset = 2.5              ; X轴偏移量（米，车辆前进方向）
y_offset = -0.8             ; Y轴偏移量（米，车辆横向,左正右负）
z_offset = 0.3              ; Z轴偏移量（米，垂直方向，向上为正）
yaw_angle = 0.0             ; 偏航角（度）
pitch_angle = 0.0           ; 俯仰角（度）
roll_angle = 0.0            ; 翻滚角（度）
